version: '3'

services:

  app:
    build: .
    restart: "always"
    working_dir: /in-docker
    volumes:
      # PHP Configs
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro

      # Application
      - ./app:/in-docker/app:cached
      - ./i18n:/in-docker/i18n:cached
      - ./assets/dynamic:/in-docker/assets/dynamic:cached
      - ./www:/in-docker/www:cached
      - ./log:/in-docker/log:cached
      - ./temp:/in-docker/temp:cached
      - ./vendor:/in-docker/vendor:cached
    expose:
      - 9000
    networks:
      - wakers-network


  nginx:
    image: nginx:1.15.4-alpine
    restart: "always"
    volumes:
      # Nginx config
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/servers/production.conf:/etc/nginx/servers/production.conf:ro
      - ./docker/nginx/servers/development.conf:/etc/nginx/servers/development.conf:ro

      # Certbot certificates
      - ./docker/certbot.local/conf:/etc/letsencrypt:cached
      - ./docker/certbot.local/www:/var/www/certbot:cached

      # Application
      - ./app:/in-docker/app:cached
      - ./assets/dynamic:/in-docker/assets/dynamic:cached
      - ./www:/in-docker/www:cached
      - ./log:/in-docker/log:cached
      - ./temp:/in-docker/temp:cached
      - ./vendor:/in-docker/vendor:cached
    networks:
      - wakers-network
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - app


  certbot:
    image: certbot/certbot
    volumes:
      # Certbot certificates
      - ./docker/certbot.local/conf:/etc/letsencrypt:cached
      - ./docker/certbot.local/www:/var/www/certbot:cached
      - ./docker/certbot.local/log:/var/log/letsencrypt:cached
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - wakers-network
    depends_on:
      - nginx


  mariadb:
    image: mariadb:10.4.2
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: wakers_cms_db
    volumes:
      # Config
      - ./docker/mariadb/config.cnf:/etc/mysql/conf.d/custom.cnf
      # Mariadb folder
      - ./docker/mariadb.local:/var/lib/mysql:cached
      # Dumps
      - ./docker/mariadb:/dumps:cached
    networks:
      - wakers-network


  adminer:
    image: dockette/adminer:dg
    restart: "always"
    ports:
      - 9876:80
    networks:
      - wakers-network


  sftp:
    restart: "always"
    image: atmoz/sftp:alpine-3.7
    volumes:
      - ./docker/mariadb:/home/${SFTP_USER}/docker/mariadb:ro
      - ./assets/dynamic:/home/${SFTP_USER}/assets/dynamic
      - ./log:/home/${SFTP_USER}/log
      - ./temp/cache:/home/${SFTP_USER}/temp/cache
      - ./www/temp:/home/${SFTP_USER}/www/temp
    ports:
      - "2222:22"
    command: ${SFTP_USER}:${SFTP_PASSWORD}:1001
    networks:
      - wakers-network


networks:
  wakers-network:
